/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.karlivanpetter.gameoflife;

import se.karlivanpetter.gameoflife.core.Board;
import se.karlivanpetter.gameoflife.ui.BoardDisplay;
import se.karlivanpetter.gameoflife.ui.console.ConsoleBoardDisplay;

import static se.karlivanpetter.gameoflife.ui.console.ConsoleUtils.clearScreen;

public class GameOfLife {

    public static void main(String[] args) throws Exception {
        Configuration config = Configuration.parse(args);
        Board b = Board.init(config.getRows(), config.getColumns(), config.getProbability());
        BoardDisplay display = new ConsoleBoardDisplay();

        for (int i = 0; i < config.getIterations(); i++) {
            clearScreen();
            System.out.println("Generation " + (i + 1) + "/" + config.getIterations());
            display.display(b);
            System.out.println();
            b = b.getNextGeneration();
            Thread.sleep(1000);
        }
    }
}
